KAFKA_CLUSTERS_0_NAME=local
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:29091
KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://localhost:8085
KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_USERNAME=username
KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_PASSWORD=password
KAFKA_CLUSTERS_0_METRICS_PORT=9997
KAFKA_CLUSTERS_0_METRICS_TYPE=JMX