spring.application.name=consumer-service
spring.kafka.consumer.bootstrap-servers:
spring.kafka.consumer.group-id:  
spring.kafka.consumer.key-deserializer:
spring.kafka.consumer.value-deserializer:
server.port=0