spring.application.name=streams-service
spring.kafka.bootstrap-servers:
spring.kafka.streams.application-id:
spring.kafka.streams.properties.default.key.serde: 
spring.kafka.streams.properties.default.value.serde: