spring:
  kafka:
    streams:
      bootstrap-servers: kafka0:9092
      application-id: streams-service
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  application:
    name: streams-service

server:
  port: 8086
logging:
  level:
    org.springframework.kafka: DEBUG